[package]
name = "tuisv"
version = "0.0.0"
edition = "2024"
description = "A small, read-only CSV and TSV viewer for the terminal"
license = "MIT"
repository = "https://github.com/mevanlc/tuisv"
readme = "README.md"
keywords = ["csv", "tsv", "tui", "viewer", "terminal"]
categories = ["command-line-utilities"]
include = ["/src/**", "/samples/**", "/Cargo.toml", "/Cargo.lock", "/README.md", "/LICENSE"]

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29.0"
csv = "1.4.0"
fancy-regex = "0.18.0"
ratatui = { version = "0.30.2", features = ["palette", "scrolling-regions"] }
ratatui-textarea = "0.9.2"
unicode-width = "0.2.2"
